"""Append remaining dashboard tabs to index.html (Phase 3)."""
import pathlib

OUT = pathlib.Path(r"f:\Brain-5D\src\dashboard\static\index.html")

# Read existing content
existing = OUT.read_text(encoding="utf-8")

# The file ends with </section> <!-- /tab-overview --> followed by newlines
# We need to remove any trailing content after /tab-overview and replace with everything else

# Build remaining tabs
lines = []

def al(s=""):
    lines.append(s)

# ===== NETWORK TAB =====
al()
al('    <!-- ========================================================== -->')
al('    <!-- TAB: NETWORK (all scientific visualizations) -->')
al('    <!-- ========================================================== -->')
al('    <section class="tab-content" id="tab-network">')
al('      <!-- Heatmap + 5D Projection -->')
al('      <section class="card heatmap-panel">')
al('        <div class="panel-title">')
al('          <div><h2>5D Netzwerk-Projektion</h2><p><span id="source-badge" class="badge badge-live">LIVE</span> &middot; Live Runtime oder Snapshot</p></div>')
al('          <div class="button-group">')
al('            <button id="live-toggle" class="active" title="Umschalten zwischen Live Runtime und Snapshot">&#x1F504; LIVE</button>')
al('            <button data-kind="activity" class="active">Aktivit&auml;t</button>')
al('            <button data-kind="energy">Energie</button>')
al('            <button data-kind="membrane">Membran</button>')
al('            <button data-kind="spike">Spikes</button>')
al('            <button data-kind="weight">Gewichte</button>')
al('          </div>')
al('        </div>')
al('        <div class="heatmap-split">')
al('          <div class="heatmap-wrap"><canvas id="heatmap" width="800" height="420"></canvas><div class="heatmap-meta" id="heatmap-meta">Keine Live-Verbindung.</div></div>')
al('          <div class="projection-wrap"><canvas id="projection-5d" width="400" height="420"></canvas><div class="heatmap-meta">5D Isometrische Projektion</div></div>')
al('        </div>')
al('      </section>')
al('      <!-- IO-Fluss -->')
al('      <section class="card io-flow-panel">')
al('        <div class="panel-title"><div><h2>&#x1F500; Input-Output Fluss</h2><p>Signalpropagation durch das Netzwerk</p></div><span id="io-flow-badge" class="gate-badge pending">&#x23F3;</span></div>')
al('        <div class="io-flow-grid">')
al('          <div class="io-flow-layer io-input"><div class="io-layer-header">Input <span id="io-input-count">0</span></div><div class="io-layer-bar"><div class="io-layer-fill" id="io-input-fill"></div></div><div class="io-layer-rate"><span id="io-input-rate">0.000</span> spikes/tick</div></div>')
al('          <div class="io-flow-arrow">&rarr;</div>')
al('          <div class="io-flow-layer io-hidden"><div class="io-layer-header">Hidden <span id="io-hidden-count">0</span></div><div class="io-layer-bar"><div class="io-layer-fill" id="io-hidden-fill"></div></div><div class="io-layer-rate"><span id="io-hidden-rate">0.000</span> spikes/tick</div></div>')
al('          <div class="io-flow-arrow">&rarr;</div>')
al('          <div class="io-flow-layer io-output"><div class="io-layer-header">Output <span id="io-output-count">0</span></div><div class="io-layer-bar"><div class="io-layer-fill" id="io-output-fill"></div></div><div class="io-layer-rate"><span id="io-output-rate">0.000</span> spikes/tick</div></div>')
al('        </div>')
al('        <div class="io-flow-meta" id="io-flow-meta">&#x23F3; Lade Daten...</div>')
al('      </section>')
al('      <!-- Populationen -->')
al('      <section class="card population-panel">')
al('        <div class="panel-title"><div><h2>&#x1F465; Neuronale Populationen</h2><p>E/I-Ratio, Aktivit&auml;t pro Typ</p></div><span id="ei-ratio-badge" class="gate-badge">E/I: &mdash;</span></div>')
al('        <div class="population-grid" id="population-grid"><div class="population-empty">&#x23F3; Lade Populationsdaten...</div></div>')
al('        <div class="population-meta" id="population-meta">Aktualisiert: &mdash;</div>')
al('      </section>')
al('      <!-- Spike Raster -->')
al('      <section class="card raster-panel">')
al('        <div class="panel-title"><div><h2>&#x26A1; Spike Raster</h2><p>Letzte 100 Ticks &middot; aktivste Neuronen</p></div><span id="raster-badge" class="gate-badge pending">&#x23F3;</span></div>')
al('        <canvas id="spike-raster" width="900" height="380"></canvas>')
al('        <div class="heatmap-meta" id="raster-meta">&#x23F3; Lade Spike-Daten...</div>')
al('      </section>')
al('      <!-- Firing Rate Histogram -->')
al('      <section class="card histogram-panel">')
al('        <div class="panel-title"><div><h2>&#x1F4CA; Feuerraten-Histogramm</h2><p>Verteilung der neuronalen Aktivit&auml;t</p></div><span id="histogram-stats" class="gate-badge">&mdash;</span></div>')
al('        <canvas id="rate-histogram" width="900" height="300"></canvas>')
al('        <div class="heatmap-meta" id="histogram-meta">&#x23F3; Lade Histogramm-Daten...</div>')
al('      </section>')
al('      <!-- 5D Layer Explorer -->')
al('      <section class="card layer-explorer-panel">')
al('        <div class="panel-title"><div><h2>&#x1F90A; 5D Layer Explorer</h2><p>Slice durch den 5D-Raum</p></div><span id="layer-badge" class="gate-badge">d4</span></div>')
al('        <div class="layer-controls">')
al('          <label>Dimension: <select id="layer-dim"><option value="z">Z (r&auml;umlich)</option><option value="d4">d4 (funktional)</option><option value="d5">d5 (funktional)</option></select></label>')
al('          <label>Layer: <input type="range" id="layer-slider" min="0" max="255" value="128" /><span id="layer-value">128</span></label>')
al('          <label>Anzeige: <select id="layer-kind"><option value="activity">Aktivit&auml;t</option><option value="energy">Energie</option><option value="membrane">Membran</option></select></label>')
al('        </div>')
al('        <canvas id="layer-canvas" width="400" height="400"></canvas>')
al('        <div class="heatmap-meta" id="layer-meta">W&auml;hle Dimension und Layer</div>')
al('      </section>')
al('      <!-- Network Inspector -->')
al('      <section class="card panel">')
al('        <div class="panel-title"><h2>&#x1F9E0; Network Inspector <span class="provenance-badge" data-src="LIVE">LIVE</span></h2><button id="inspect-refresh" type="button" class="btn-secondary">&#x1F504; Refresh</button></div>')
al('        <dl class="kv" id="inspect-network-summary">')
al('          <div><dt>Dimensions</dt><dd id="inspect-dimensions">&mdash;</dd></div>')
al('          <div><dt>Neurons</dt><dd id="inspect-neuron-count">&mdash;</dd></div>')
al('          <div><dt>Synapses</dt><dd id="inspect-synapse-count">&mdash;</dd></div>')
al('          <div><dt>Input cells</dt><dd id="inspect-input-count">&mdash;</dd></div>')
al('          <div><dt>Output cells</dt><dd id="inspect-output-count">&mdash;</dd></div>')
al('          <div><dt>Active neurons</dt><dd id="inspect-active-neurons">&mdash;</dd></div>')
al('          <div><dt>Silent neurons</dt><dd id="inspect-silent-neurons">&mdash;</dd></div>')
al('          <div><dt>Queue depth</dt><dd id="inspect-queue-depth">&mdash;</dd></div>')
al('          <div><dt>Tick</dt><dd id="inspect-tick">&mdash;</dd></div>')
al('          <div><dt>Total spikes</dt><dd id="inspect-total-spikes">&mdash;</dd></div>')
al('          <div><dt>Mean energy</dt><dd id="inspect-mean-energy">&mdash;</dd></div>')
al('          <div><dt>Mean v</dt><dd id="inspect-mean-v">&mdash;</dd></div>')
al('        </dl>')
al('      </section>')
al('      <!-- 5D Projection -->')
al('      <section class="card panel">')
al('        <div class="panel-title"><h2>&#x1F310; 5D Coordinate Inspector <span class="provenance-badge" data-src="LIVE">LIVE</span></h2>')
al('          <div class="button-group"><select id="projection-mode"><option value="activity">Activity (spike count)</option><option value="energy">Energy</option><option value="potential">Membrane potential</option></select></div>')
al('        </div>')
al('        <p class="heatmap-meta" id="projection-meta">Projection of 5D coordinates into 3D &middot; sampling live network</p>')
al('        <canvas id="inspect-projection" width="900" height="480"></canvas>')
al('      </section>')
al('      <!-- Neurons Table -->')
al('      <section class="card panel">')
al('        <div class="panel-title"><h2>&#x1F52C; Neurons <span class="provenance-badge" data-src="LIVE">LIVE</span></h2>')
al('          <div class="button-group">')
al('            <label class="input-label">Limit <input id="neuron-limit" type="number" min="1" max="5000" value="200" /></label>')
al('            <label class="input-label">Offset <input id="neuron-offset" type="number" min="0" max="10000000" value="0" /></label>')
al('            <label class="input-label"><input id="neuron-active-only" type="checkbox" /> Active only</label>')
al('            <button id="neuron-load" type="button" class="btn-secondary">Load</button>')
al('          </div>')
al('        </div>')
al('        <div class="table-wrap"><table class="inspect-table"><thead><tr><th>ID</th><th>x1</th><th>x2</th><th>x3</th><th>x4</th><th>x5</th><th>v</th><th>u</th><th>energy</th><th>last_spike</th><th>spikes</th><th>I/O</th></tr></thead><tbody id="neuron-table-body"></tbody></table></div>')
al('        <p class="heatmap-meta" id="neuron-page-meta">&mdash;</p>')
al('      </section>')
al('      <!-- Synapses Table -->')
al('      <section class="card panel">')
al('        <div class="panel-title"><h2>&#x1F517; Synapses <span class="provenance-badge" data-src="LIVE">LIVE</span></h2>')
al('          <div class="button-group">')
al('            <label class="input-label">Limit <input id="synapse-limit" type="number" min="1" max="5000" value="200" /></label>')
al('            <label class="input-label">Offset <input id="synapse-offset" type="number" min="0" max="10000000" value="0" /></label>')
al('            <label class="input-label">Source <input id="synapse-source" type="number" placeholder="&mdash;" /></label>')
al('            <label class="input-label">Min weight <input id="synapse-min-weight" type="number" step="0.001" placeholder="&mdash;" /></label>')
al('            <button id="synapse-load" type="button" class="btn-secondary">Load</button>')
al('          </div>')
al('        </div>')
al('        <div class="table-wrap"><table class="inspect-table"><thead><tr><th>source</th><th>target</th><th>weight</th><th>delay</th><th>eligibility</th></tr></thead><tbody id="synapse-table-body"></tbody></table></div>')
al('        <p class="heatmap-meta" id="synapse-page-meta">&mdash;</p>')
al('      </section>')
al('    </section> <!-- /tab-network -->')

OUT.write_text(existing + "\n".join(lines), encoding="utf-8")
print(f"Appended NETWORK tab. File size: {OUT.stat().st_size}")
