"""Append CONTROL, RESEARCH&DOCS, RELEASE tabs + footer to index.html."""
import pathlib

OUT = pathlib.Path(r"f:\Brain-5D\src\dashboard\static\index.html")
existing = OUT.read_text(encoding="utf-8")

M = []  # lines to append

def a(s=""):
    M.append(s)

# ===== CONTROL & CONSOLE =====
a()
a('    <!-- ========================================================== -->')
a('    <!-- TAB: CONTROL & CONSOLE -->')
a('    <!-- ========================================================== -->')
a('    <section class="tab-content" id="tab-control">')
a('      <!-- Runtime Control -->')
a('      <section class="control-card" id="runtime-control-card">')
a('        <div class="control-card__header">')
a('          <div class="control-card__title-group"><h2 id="runtime-control-title">Runtime Control</h2><p class="control-card__subtitle">Step execution, loop control, pacing, snapshots &amp; structural gates</p></div>')
a('          <span class="runtime-state" id="runtime-state" role="status">unknown</span>')
a('        </div>')
a('        <div class="runtime-metrics">')
a('          <div class="metric-item"><span class="metric-label">Tick</span><strong class="metric-value" id="runtime-tick">0</strong></div>')
a('          <div class="metric-item"><span class="metric-label">Queued</span><strong class="metric-value" id="runtime-queued">0</strong></div>')
a('          <div class="metric-item"><span class="metric-label">Batch</span><strong class="metric-value" id="runtime-last-batch">0</strong></div>')
a('          <div class="metric-item"><span class="metric-label">Batch ms</span><strong class="metric-value" id="runtime-last-ms">0.0</strong></div>')
a('        </div>')
a('        <div class="control-grid">')
a('          <div class="control-group step-group">')
a('            <div class="control-group__header"><span class="control-group__title">Step</span><span class="shortcut-hint">Ctrl+Shift+S</span></div>')
a('            <div class="control-group__body"><label class="input-label" for="step-ticks">Ticks <input id="step-ticks" type="number" min="1" max="10000000" value="1" /></label><button id="step-button" type="button" class="btn-primary">Step</button></div>')
a('          </div>')
a('          <div class="control-group run-group">')
a('            <div class="control-group__header"><span class="control-group__title">Run Loop</span><span class="shortcut-hint">Ctrl+Shift+R</span></div>')
a('            <div class="control-group__body"><label class="input-label" for="loop-size">Loop size <input id="loop-size" type="number" min="1" max="1000000" value="100" /></label><button id="run-button" type="button" class="btn-success">Run</button></div>')
a('          </div>')
a('          <div class="control-group config-group">')
a('            <div class="control-group__header"><span class="control-group__title">Configure</span></div>')
a('            <div class="control-group__body"><label class="input-label" for="delay-ms">Delay/tick (ms) <input id="delay-ms" type="number" min="0" max="60000" step="0.1" value="0" /></label><button id="apply-runtime-config" type="button" class="btn-secondary">Apply</button></div>')
a('          </div>')
a('          <div class="control-group actions-group">')
a('            <div class="control-group__header"><span class="control-group__title">Control</span></div>')
a('            <div class="control-group__body actions-row">')
a('              <button id="pause-button" type="button" class="btn-warning">Pause</button>')
a('              <button id="snapshot-button" type="button" class="btn-info">Snapshot</button>')
a('              <button id="stop-button" type="button" class="btn-danger">Stop</button>')
a('            </div>')
a('          </div>')
a('        </div>')
a('        <details class="self-org-section" id="self-org-section">')
a('          <summary class="self-org-summary"><h3>Self-Organization Gate</h3><span class="badge" id="self-org-status-badge">checking...</span></summary>')
a('          <div class="self-org-controls">')
a('            <div class="self-org-row"><label class="switch-line" for="self-org-enabled"><input id="self-org-enabled" type="checkbox" checked /><span class="switch-line__label">Policy enabled</span><span class="switch-line__help">Allow structural changes</span></label><label class="switch-line" for="self-org-dry-run"><input id="self-org-dry-run" type="checkbox" checked /><span class="switch-line__label">Dry-run mode</span><span class="switch-line__help">Simulate without applying</span></label></div>')
a('            <div class="proposal-line"><span class="proposal-label">Last proposal</span><strong id="self-org-proposal">none</strong><span id="self-org-proposal-time" class="proposal-time"></span></div>')
a('            <div class="proposal-actions"><button id="btn-undo-structural" type="button" class="btn-small undo">Undo last change</button><button id="btn-auto-approval" type="button" class="btn-small auto-approval" data-enabled="false">Enable Auto-Approval</button></div>')
a('          </div>')
a('        </details>')
a('        <output id="control-message" class="control-message" aria-live="polite">Ready</output>')
a('      </section>')
a('      <!-- Operator Console -->')
a('      <section class="card operator-console" id="operator-console">')
a('        <div class="console-header">')
a('          <div class="console-title-group"><h2 id="console-title">Operator Console</h2><p class="console-subtitle">Step execution, loop control, structural proposals &amp; system monitoring</p></div>')
a('          <div class="console-status-group"><span class="status-badge" id="b5d-state-badge">idle</span><span class="tick-display" id="b5d-tick-display">0</span></div>')
a('        </div>')
a('        <div class="console-metrics" id="b5d-metrics" role="group">')
a('          <span class="metric">Neurons <span id="metric-neurons">0</span></span>')
a('          <span class="metric">Synapses <span id="metric-synapses">0</span></span>')
a('          <span class="metric">Spikes <span id="metric-spikes">0</span></span>')
a('          <span class="metric">Queue <span id="metric-queue">0</span></span>')
a('        </div>')
a('        <div class="console-controls">')
a('          <div class="control-group"><div class="control-group__header"><span class="control-group__title">Step</span><span class="shortcut-hint">Ctrl+Enter</span></div><div class="control-group__body"><button id="b5d-step" class="btn-primary">+1 Tick</button></div></div>')
a('          <div class="control-group"><div class="control-group__header"><span class="control-group__title">Run N Ticks</span></div><div class="control-group__body"><label class="input-label" for="b5d-tick-count"><input id="b5d-tick-count" type="number" min="1" max="10000000" value="100" /></label><button id="b5d-run-ticks" class="btn-success">Run</button></div></div>')
a('          <div class="control-group"><div class="control-group__header"><span class="control-group__title">Runtime</span></div><div class="control-group__body actions-row"><button id="b5d-start" class="btn-success">Start</button><button id="b5d-pause" class="btn-warning">Pause</button><button id="b5d-resume" class="btn-primary">Resume</button><button id="b5d-stop" class="btn-danger">Stop</button></div></div>')
a('          <div class="control-group"><div class="control-group__header"><span class="control-group__title">Utilities</span></div><div class="control-group__body actions-row"><button id="b5d-snapshot" class="btn-info">Snapshot</button><button id="b5d-undo" class="btn-undo">Undo Change</button><button id="b5d-clear-console" class="btn-secondary">Clear</button></div></div>')
a('        </div>')
a('        <details class="proposals-section" id="proposals-section">')
a('          <summary class="proposals-summary"><span class="proposals-title">Structural Proposals</span><span class="badge" id="proposals-count">0 pending</span></summary>')
a('          <div id="b5d-proposals" class="proposals-list"><div class="proposal-empty">No pending proposals</div></div>')
a('        </details>')
a('        <div class="console-output-wrapper">')
a('          <div class="console-output-header"><span class="console-output-title">Console Log</span><span class="console-output-hint">Auto-scroll &middot; Max 1000 entries</span></div>')
a('          <div id="console-output" class="console-output" role="log" aria-live="polite"><div class="log-entry log-info"><span class="log-time">[00:00:00]</span> Brain-5D Operator Console ready</div></div>')
a('        </div>')
a('        <p class="operator-note">Structural proposals remain approval-gated. No autonomous mutation is enabled by this panel.</p>')
a('      </section>')
a('      <!-- Structural Live Loop -->')
a('      <section class="card structural-live-card">')
a('        <div class="panel-title"><h2>Structural Live Loop</h2><span id="live-loop-badge" class="gate-badge pending">checking...</span></div>')
a('        <div class="structural-live-grid" id="structural-live-grid">')
a('          <div class="live-loop-item" id="ll-adapter">RuntimeAdapter</div>')
a('          <div class="live-loop-item" id="ll-signal">HomeostasisSignal</div>')
a('          <div class="live-loop-item" id="ll-policy">Policy Proposal</div>')
a('          <div class="live-loop-item" id="ll-coordinator">Coordinator</div>')
a('          <div class="live-loop-item" id="ll-approval">Approval Gate</div>')
a('          <div class="live-loop-item" id="ll-mutation">Mutation</div>')
a('          <div class="live-loop-item" id="ll-journal">Journal</div>')
a('          <div class="live-loop-item" id="ll-undo">Undo</div>')
a('          <div class="live-loop-item" id="ll-replay">Replay</div>')
a('        </div>')
a('        <p class="heatmap-meta" id="live-loop-meta">Requires poc_structural_live.yaml config</p>')
a('      </section>')
a('    </section> <!-- /tab-control -->')

# ===== RESEARCH & DOCS =====
a()
a('    <!-- ========================================================== -->')
a('    <!-- TAB: RESEARCH & DOCS -->')
a('    <!-- ========================================================== -->')
a('    <section class="tab-content" id="tab-research">')
a('      <div class="research-docs-split">')
a('        <!-- Research side -->')
a('        <div class="research-browser">')
a('          <div class="research-sidebar">')
a('            <div class="research-toolbar"><h3>B5D Scientific Evidence Framework</h3><div id="research-summary" class="research-summary"><span class="research-stat">Initialisiere Research-Quelle...</span></div></div>')
a('            <div class="research-section"><h4>Generated Reports</h4><div id="research-reports" class="research-list"><span class="research-empty">Wird geladen...</span></div></div>')
a('            <div class="research-section"><h4>Registry</h4><div id="research-documents" class="research-docs"><span class="research-empty">Wird geladen...</span></div></div>')
a('            <div class="research-section"><h4>Experiments</h4><div id="research-experiments" class="research-list"><span class="research-empty">Wird geladen...</span></div></div>')
a('          </div>')
a('          <div id="research-viewer" class="research-viewer">')
a('            <div class="research-placeholder"><p>Select a research document to view its contents.</p><p class="research-hint">B5D-SEF registry: 27 Research Questions &middot; 27 Hypotheses &middot; 5 Claims &middot; 8 Sources &middot; 13 Methods</p></div>')
a('          </div>')
a('        </div>')
a('        <!-- Docs side -->')
a('        <div class="doc-browser">')
a('          <div class="doc-sidebar">')
a('            <div class="doc-toolbar"><input type="text" id="doc-search" placeholder="Search documents..." /><div id="doc-filter-container"></div><button id="doc-refresh">Refresh</button></div>')
a('            <div id="doc-stats" class="doc-stats">Lade Dokumentation...</div>')
a('            <div id="doc-tree" class="doc-tree">Lade Verzeichnisstruktur...</div>')
a('          </div>')
a('          <div id="doc-viewer" class="doc-viewer">')
a('            <div class="doc-placeholder"><p>Select a document to view its contents.</p><p style="color: #888; font-size: 13px;">Supported formats: Markdown, Text, DOCX, XLSX, CSV, JSON, PDF (metadata)</p></div>')
a('          </div>')
a('        </div>')
a('      </div>')
a('    </section> <!-- /tab-research -->')

# ===== RELEASE (Alpha.5 Gate) =====
a()
a('    <!-- ========================================================== -->')
a('    <!-- TAB: RELEASE (Alpha.5 Gate) -->')
a('    <!-- ========================================================== -->')
a('    <section class="tab-content" id="tab-gate">')
a('      <div class="gate-board">')
a('        <div class="gate-header">')
a('          <h2>Alpha.5 Release Gate</h2>')
a('          <p class="gate-subtitle">Alpha.5 is complete only when all Gate A, B and C criteria pass. <span class="gate-rule">Do not advance to alpha.6 while this gate is open.</span></p>')
a('          <p class="gate-legend"><strong>Live</strong> = current runtime config state &middot; <strong>Maturity</strong> = IMPLEMENTED &rarr; INTEGRATED &rarr; VERIFIED &rarr; EVIDENCED &middot; <strong>Gate</strong> = release verification result. Runtime disabled &ne; gate failed. Runtime disabled &ne; gate passed.</p>')
a('          <button id="gate-refresh" type="button" class="btn-secondary">Re-check</button>')
a('        </div>')
a('        <div class="gate-overall-row"><strong>ALPHA.5 Overall:</strong><span class="gate-badge pending" id="gate-overall">pending</span></div>')
a('        <div class="gate-section"><h3>Live Runtime Profile <span class="gate-section-hint">(current config)</span></h3><div id="gate-live-list" class="gate-live-grid"></div></div>')
a('        <div class="gate-section"><h3>Gate A &mdash; Technical Integration</h3><div id="gate-a-list" class="gate-criteria-table"></div></div>')
a('        <div class="gate-section"><h3>Gate B &mdash; Verification</h3><div id="gate-b-list" class="gate-criteria-table"></div></div>')
a('        <div class="gate-section"><h3>Gate C &mdash; Scientific Baseline</h3><div id="gate-c-list" class="gate-criteria-table"></div></div>')
a('      </div>')
a('    </section> <!-- /tab-gate -->')
a()
a('  </main>')

# ===== MODAL =====
a('  <!-- Integration Status Modal -->')
a('  <div id="integration-modal" class="modal-overlay" style="display:none;">')
a('    <div class="modal-content">')
a('      <div class="modal-header"><h2>Integration Status &ndash; Alle Versionen</h2><button class="modal-close" id="modal-close-btn" aria-label="Close">&times;</button></div>')
a('      <div class="modal-body" id="integration-modal-body"><div class="modal-loading">Lade Integrationsdaten...</div></div>')
a('      <div class="modal-footer"><button class="btn-secondary" id="modal-refresh-btn">Aktualisieren</button><button class="btn-primary" id="modal-close-btn2">Schlie&szlig;en</button></div>')
a('    </div>')
a('  </div>')
a('')
a('  <!-- Footer -->')
a('  <footer>Brain-5D Operator Dashboard &middot; lokal &middot; interaktiv &middot; v0.5.0-alpha.5</footer>')
a('')
a('  <!-- Scripts -->')
a('  <script type="module" src="/app.js"></script>')
a('</body>')
a('</html>')
a('')
a('')
# ===== WRITE =====
OUT.write_text(existing + "\n".join(M), encoding="utf-8")
print(f"Written. File size: {OUT.stat().st_size}")