"""Alpha.5 Structural Live Loop E2E test.

This test proves the production path for the first real closed structural
regulation loop. It uses the production composition/runtime adapter path
and the dedicated live config (configs/poc_structural_live.yaml).

Required sequence:

A. Start real network/runtime with structural live config.
B. Confirm:
   - Homeostasis active
   - Self-Organization active
   - Coordinator active
   - PlasticityEngine active
   - StructuralJournal active
   - RuntimeAdapter attached
C. Advance real ticks through RuntimeController.
D. Obtain a proposal generated by:
   real Network -> real HomeostasisSignal -> production RuntimeAdapter
   -> SelfOrganizationPolicy -> Coordinator
E. Capture canonical topology digest before proposal.
F. Verify proposal exists.
G. Verify topology digest is unchanged before approval.
H. Verify proposal is observable through OperatorBridge.
I. Reject one proposal:
   - rejection succeeds
   - topology unchanged
   - no mutation StructuralChangeRecord produced for rejection
J. Generate another real proposal.
K. Approve exactly one proposal.
L. Verify:
   - exactly one expected structural mutation
   - topology digest changes
   - exactly one committed StructuralChangeRecord for that mutation
   - proposal_id linkage matches
   - tick/provenance fields are present where supported
M. Continue runtime for additional ticks after mutation.
   The network must remain operable.
N. Undo:
   - inverse-record path used
   - topology digest returns exactly to pre-mutation structural digest
O. Re-open StructuralJournal from disk in a fresh instance and replay
   into a fresh equivalent base network. Verify topology identity for
   the applicable post-mutation state.

IMPORTANT:
Structural digest remains structural only:
- neuron id
- coordinate
- synapse source
- synapse target
- weight
- delay

Do not include v/u/energy in the structural digest.
Full dynamic state equality belongs to Restore Determinism later.
"""

from __future__ import annotations

import hashlib
import json
import random
from pathlib import Path
from typing import Any

import pytest

from src.config.loader import load_config
from src.controller.runtime import RuntimeController
from src.core import Brain5DConfig, NeuralNetwork
from src.core.spatial_index import linear_to_5d, unpack_coords
from src.dashboard.operator_bridge import OperatorBridge
from src.homeostasis.engine import HomeostasisEngine
from src.self_organization.composition import compose_structural_subsystem
from src.self_organization.policy import (
    SelfOrganizationPolicy,
    SelfOrganizationPolicyConfig,
)
from src.self_organization.runtime_adapter import (
    SelfOrganizationRuntimeAdapter,
    get_error_buffer,
)
from src.storage.structural_journal import (
    StructuralChangeKind,
    StructuralJournal,
)


# =========================================================================
# Structural digest (structural only -- no dynamic state)
# =========================================================================


def _structural_digest(network: Any) -> str:
    """SHA-256 over canonical structural representation.

    Includes only structural identity fields:
    - neurons: neuron_id, coord
    - synapses: source_id, target_id, weight, delay

    Does NOT include dynamic state (v, u, energy, spike counters).
    """
    neuron_ids = sorted(network.neurons.keys())
    neurons_canonical: list[dict[str, Any]] = []
    for nid in neuron_ids:
        neurons_canonical.append({
            "neuron_id": nid,
            "coord": list(unpack_coords(nid)),
        })

    synapses_canonical: list[dict[str, Any]] = []
    for source_id in sorted(network.synapses.keys()):
        syn_list = sorted(
            network.synapses[source_id],
            key=lambda s: (int(s.target_id), int(s.delay), float(s.weight)),
        )
        for syn in syn_list:
            synapses_canonical.append({
                "source_id": source_id,
                "target_id": int(syn.target_id),
                "weight": float(syn.weight),
                "delay": int(syn.delay),
            })

    canonical = {
        "neuron_count": len(neuron_ids),
        "synapse_count": len(synapses_canonical),
        "neurons": neurons_canonical,
        "synapses": synapses_canonical,
    }
    raw = json.dumps(canonical, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


# =========================================================================
# Live config path
# =========================================================================

_LIVE_CONFIG = Path(__file__).resolve().parents[1] / "configs" / "poc_structural_live.yaml"


# =========================================================================
# Helper: build network from the live config
# =========================================================================


def _build_network_from_config(config_dict: dict[str, Any]) -> NeuralNetwork:
    """Build a NeuralNetwork from a config dict, same as src.main."""
    config = Brain5DConfig.from_dict(config_dict)
    rng = random.Random(int(config_dict.get("seed", 42)))
    network = NeuralNetwork(config, rng)
    dims = config.dimensions

    total_positions = 1
    for d in dims:
        total_positions *= d

    initial_neurons = int(config_dict.get("initial_neurons", 100))
    chosen = random.Random(42).sample(range(total_positions), initial_neurons)

    for idx in sorted(chosen):
        network.add_neuron(linear_to_5d(idx, dims))

    conn_per_neuron = config.network.initial_connections_per_neuron
    radius = config.network.neighbour_radius
    network.initialize_random_connections(conn_per_neuron, radius)
    return network


# =========================================================================
# TEST: Structural Live Loop
# =========================================================================


@pytest.fixture
def live_config() -> dict[str, Any]:
    """Load the dedicated live config.

    Uses the raw YAML loader to get all sections (the validated loader
    strips homeostasis, self_organization, and storage sections).
    """
    import yaml
    config_dict: dict[str, Any] = load_config(str(_LIVE_CONFIG))
    # Merge raw sections that the validated loader strips
    with open(str(_LIVE_CONFIG), "r", encoding="utf-8") as f:
        raw = yaml.safe_load(f) or {}
    for key in ("homeostasis", "self_organization", "storage", "eligibility", "max_neurons"):
        if key in raw:
            config_dict[key] = raw[key]
    return config_dict


def test_structural_live_loop(tmp_path: Path, live_config: dict[str, Any]) -> None:
    """Complete Alpha.5 structural live loop E2E test.

    This test proves the entire production path:
    real Network -> real ticks -> real HomeostasisSignal
    -> config-authoritative Policy -> real Proposal -> Coordinator
    -> no mutation before approval -> OperatorBridge -> manual approval
    -> exactly one mutation -> journal -> undo -> replay
    """
    # Clear error buffer before starting
    get_error_buffer().clear()

    # ====================================================================
    # A. Build network and runtime with structural live config
    # ====================================================================
    network = _build_network_from_config(live_config)

    # Create and attach homeostasis
    homeostasis = HomeostasisEngine(network, live_config)
    assert homeostasis.enabled, "Homeostasis must be enabled in live config"
    homeostasis.attach()

    # ====================================================================
    # B. Confirm all components are active
    # ====================================================================
    so_cfg = live_config.get("self_organization", {})
    _allow_neurogenesis = bool(so_cfg.get("neurogenesis_enabled", True))
    _allow_neuron_pruning = bool(so_cfg.get("pruning_enabled", False))
    _allow_synapse_sprouting = bool(so_cfg.get("sprouting_enabled", False))
    _allow_synapse_pruning = bool(so_cfg.get("synapse_pruning_enabled", False))

    journal_path = tmp_path / "structural_live.journal"
    composed = compose_structural_subsystem(
        network,
        journal_path,
        coordinator_enabled=True,
        coordinator_dry_run=False,
        max_changes_per_tick=1,
        allow_neurogenesis=_allow_neurogenesis,
        allow_neuron_pruning=_allow_neuron_pruning,
        allow_synapse_sprouting=_allow_synapse_sprouting,
        allow_synapse_pruning=_allow_synapse_pruning,
        create_controller=True,
        create_bridge=True,
    )
    plasticity = composed["plasticity"]
    coordinator = composed["coordinator"]
    journal = composed["journal"]
    bridge = composed["bridge"]
    controller = composed["controller"]  # Use the controller from composition

    assert coordinator is not None
    assert plasticity is not None
    assert journal is not None
    assert bridge is not None
    assert controller is not None

    # Attach the RuntimeAdapter with config-authoritative settings
    policy_config = SelfOrganizationPolicyConfig.from_config(live_config)
    adapter = SelfOrganizationRuntimeAdapter(
        homeostasis_engine=homeostasis,
        coordinator=coordinator,
        interval_ticks=int(so_cfg.get("interval_ticks", 50)),
        policy_config=policy_config,
    )
    controller.add_hook(adapter)

    # ====================================================================
    # C. Advance real ticks
    # ====================================================================
    controller.run_ticks(300)

    # ====================================================================
    # D. Check that a proposal was generated from real measurements
    # ====================================================================
    report = coordinator.latest()
    if report is None or len(report.proposals) == 0:
        controller.run_ticks(300)
        report = coordinator.latest()

    if report is None or len(report.proposals) == 0:
        controller.run_ticks(400)
        report = coordinator.latest()

    assert report is not None, (
        "No PolicyReport produced after 1000 ticks. "
        "Check that homeostasis is generating a signal and the adapter is attached."
    )
    assert len(report.proposals) > 0, (
        f"No proposals generated after 1000 ticks. "
        f"Neurogenesis pressure={report.neurogenesis_pressure:.3f}, "
        f"enabled={policy_config.neurogenesis_enabled}"
    )

    proposal = report.proposals[0]
    assert proposal.kind.value == "neurogenesis", (
        f"Expected neurogenesis proposal, got {proposal.kind}"
    )
    assert proposal.reason, "Proposal must have a reason string"
    assert proposal.confidence > 0.0, "Proposal must have positive confidence"

    # Verify the adapter has no errors
    error_buffer = get_error_buffer()
    assert error_buffer.count == 0, (
        f"RuntimeAdapter produced {error_buffer.count} errors: "
        f"{[e.message for e in error_buffer.events]}"
    )

    # ====================================================================
    # E. Capture topology digest before proposal
    # ====================================================================
    digest_before = _structural_digest(network)

    # ====================================================================
    # F. Verify proposal exists in coordinator
    # ====================================================================
    proposal_id = proposal.proposal_id
    found = coordinator.find(proposal_id)
    assert found is not None, f"Proposal {proposal_id} not found in coordinator"

    # ====================================================================
    # G. Verify topology is unchanged before approval
    # ====================================================================
    digest_still_before = _structural_digest(network)
    assert digest_before == digest_still_before, (
        "Topology changed before approval -- unexpected mutation"
    )

    # ====================================================================
    # H. Verify proposal observable through OperatorBridge
    # ====================================================================
    bridge_proposals = bridge.structural_proposals()
    bridge_ids = [p["proposal_id"] for p in bridge_proposals]
    assert proposal_id in bridge_ids, (
        f"Proposal {proposal_id} not found in OperatorBridge proposals: {bridge_ids}"
    )

    # ====================================================================
    # I. Reject one proposal
    # ====================================================================
    reject_result = bridge.reject_structural(proposal_id)
    assert reject_result.ok, f"Rejection failed: {reject_result.message}"

    digest_after_reject = _structural_digest(network)
    assert digest_after_reject == digest_before, "Topology changed after rejection"

    history_after_reject = journal.history(100)
    assert len(history_after_reject) == 0, (
        f"Journal has records after rejection (expected 0): {len(history_after_reject)}"
    )

    # ====================================================================
    # J. Generate another real proposal (continue running)
    # ====================================================================
    controller.run_ticks(200)

    report2 = coordinator.latest()
    assert report2 is not None, "No report after additional ticks"
    assert len(report2.proposals) > 0, "No proposals after additional ticks"

    # Must approve from the CURRENT latest report
    proposal2 = report2.proposals[0]
    proposal2_id = proposal2.proposal_id
    assert proposal2_id != proposal_id, "Same proposal ID -- expected a new proposal"

    # ====================================================================
    # K. Approve exactly one proposal via the bridge
    # ====================================================================
    neuron_count_before_approval = len(network.neurons)
    approve_result = bridge.apply_proposal(
        proposal2_id, approved=True
    )
    assert approve_result["ok"], f"Approval failed: {approve_result.get('error', '')}"

    # ====================================================================
    # L. Verify exactly one mutation
    # ====================================================================
    digest_after_approval = _structural_digest(network)
    assert digest_after_approval != digest_before, "Topology unchanged after approval"

    neuron_count_after = len(network.neurons)
    assert neuron_count_after == neuron_count_before_approval + 1, (
        f"Expected exactly 1 new neuron, got {neuron_count_after - neuron_count_before_approval}"
    )

    history = journal.history(100)
    assert len(history) == 1, f"Expected exactly 1 journal record, got {len(history)}"
    record = history[0]
    assert record.kind == StructuralChangeKind.NEURON_ADD, (
        f"Expected NEURON_ADD, got {record.kind}"
    )
    assert record.proposal_id == proposal2_id, (
        f"Journal proposal_id {record.proposal_id} != {proposal2_id}"
    )
    assert record.tick > 0, "Journal record tick must be > 0"
    assert record.neuron_id is not None, "Journal record must have neuron_id"

    # ====================================================================
    # M. Continue runtime after mutation -- network remains operable
    # ====================================================================
    controller.run_ticks(100)

    assert len(network.neurons) > 0, "Network has no neurons after mutation + ticks"
    # Use RuntimeController — the sole simulation-clock owner
    controller.run_ticks(1)

    # ====================================================================
    # N. Undo restores topology
    # ====================================================================
    undo_result = plasticity.undo_last_change(tick=controller.telemetry.tick + 1)
    assert undo_result is True, "Undo failed"

    digest_after_undo = _structural_digest(network)
    assert digest_after_undo == digest_before, (
        "Topology after undo does not match pre-mutation state"
    )

    history_after_undo = journal.history(100)
    assert len(history_after_undo) >= 2, (
        f"Expected at least 2 journal records after undo, got {len(history_after_undo)}"
    )
    last_record = history_after_undo[-1]
    assert last_record.kind == StructuralChangeKind.NEURON_REMOVE, (
        f"Expected NEURON_REMOVE for undo, got {last_record.kind}"
    )

    # ====================================================================
    # O. Re-open journal from disk and replay into fresh network
    # ====================================================================
    net2 = _build_network_from_config(live_config)
    journal2 = StructuralJournal(journal_path)

    composed2 = compose_structural_subsystem(
        net2,
        journal_path,
        coordinator_enabled=False,
        coordinator_dry_run=True,
    )
    plasticity2 = composed2["plasticity"]

    records = journal2.history(100)
    for rec in records:
        if rec.kind in (StructuralChangeKind.NEURON_ADD, StructuralChangeKind.SYNAPSE_ADD):
            plasticity2.apply_structural_record(rec)

    digest_after_replay = _structural_digest(net2)
    assert digest_after_replay == digest_after_approval, (
        "Replayed network topology does not match post-mutation state"
    )

    # ====================================================================
    # Verify no RuntimeAdapter errors occurred throughout
    # ====================================================================
    assert error_buffer.count == 0, (
        f"RuntimeAdapter produced {error_buffer.count} errors during live loop: "
        f"{[e.message for e in error_buffer.events]}"
    )


# =========================================================================
# Verification artifact writer for structural live loop
# =========================================================================


def test_write_live_loop_verification_artifact(tmp_path: Path) -> None:
    """Write a machine-readable live loop verification artifact.

    The artifact is written to
    ``research/generated/verification/structural_live_loop.json``
    (persistent, not gitignored) so GateStatusBuilder can verify the
    production live loop path.

    Proof IDs match REQUIRED_LIVE_LOOP_PROOFS in gate_status.py.
    """
    import platform
    import subprocess
    import sys
    from datetime import datetime

    repo_root = Path(__file__).resolve().parents[1]

    # Run the live loop test via pytest subprocess
    result = subprocess.run(
        [sys.executable, "-m", "pytest",
         "tests/test_structural_live_loop.py::test_structural_live_loop",
         "-q", "--tb=line", "--no-header"],
        capture_output=True, text=True, timeout=120,
        cwd=str(repo_root),
    )
    live_loop_passed = result.returncode == 0

    # Compute tree digest
    from src.dashboard.verification import compute_source_tree_digest, current_git_head

    tree_digest = compute_source_tree_digest(repo_root)
    commit = current_git_head(repo_root)

    proofs = {
        "production_adapter_attached": live_loop_passed,
        "real_signal_generated": live_loop_passed,
        "policy_received_real_signal": live_loop_passed,
        "proposal_published": live_loop_passed,
        "proposal_non_mutating": live_loop_passed,
        "reject_non_mutating": live_loop_passed,
        "approve_single_mutation": live_loop_passed,
        "journal_linked_to_proposal": live_loop_passed,
        "runtime_continues_after_mutation": live_loop_passed,
        "undo_restores_topology": live_loop_passed,
        "journal_reopen_replay_identity": live_loop_passed,
    }

    all_passed = all(proofs.values())

    artifact = {
        "schema_version": 1,
        "suite": "structural_live_loop",
        "status": "verified" if all_passed else "failed",
        "timestamp": datetime.now().isoformat(),
        "python_version": platform.python_version(),
        "test_run_head": commit,
        "tested_tree_digest": tree_digest,
        "test_command": "python -m pytest tests/test_structural_live_loop.py -q",
        "proofs": proofs,
    }

    verification_dir = repo_root / "research" / "generated" / "verification"
    verification_dir.mkdir(parents=True, exist_ok=True)
    artifact_path = verification_dir / "structural_live_loop.json"
    artifact_path.write_text(json.dumps(artifact, indent=2), encoding="utf-8")

    assert all_passed, (
        f"Live loop verification failed: "
        f"live_loop={live_loop_passed}"
    )
