"""Typed bridge contracts for structural dashboard endpoints."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from .models import JSONValue

JSONMapping = dict[str, JSONValue]


@dataclass(frozen=True, slots=True)
class StructuralCommandResult:
    ok: bool
    message: str


class StructuralOperatorBridge(Protocol):
    def structural_status(self) -> JSONMapping: ...
    def structural_proposals(self) -> list[JSONMapping]: ...
    def structural_history(self, limit: int) -> list[JSONMapping]: ...
    def structural_heatmap(self, kind: str) -> JSONMapping: ...
    def structural_config(self) -> JSONMapping: ...
    def approve_structural(self, proposal_id: str) -> StructuralCommandResult: ...
    def reject_structural(self, proposal_id: str) -> StructuralCommandResult: ...
    def undo_structural(self) -> StructuralCommandResult: ...
    def set_auto_approval(self, enabled: bool) -> StructuralCommandResult: ...
    def run_ticks(self, count: int) -> StructuralCommandResult: ...
    def single_step(self) -> StructuralCommandResult: ...
    def request_snapshot(self) -> StructuralCommandResult: ...
