"""One-time import data for the author-requested cognition supplement.

After import, registry fragments, protocol contracts and source records are the
editable authorities. This file is retained only as import provenance.
"""

SOURCES = [
    ("BUTLIN", "Patrick Butlin and others", 2026, "Identifying indicators of consciousness in AI systems", "10.1016/j.tics.2025.10.011", "https://www.sciencedirect.com/science/article/pii/S1364661325002864", "Publisher metadata and relevant abstract/search-accessible passages; direct full-page retry blocked", "Theory-dependent indicators; no universally sufficient consciousness test. Online 2025, journal issue June 2026; not a Brain-5D validation."),
    ("COGITATE", "Cogitate Consortium and others", 2025, "Adversarial testing of global neuronal workspace and integrated information theories of consciousness", "10.1038/s41586-025-08888-1", "https://www.nature.com/articles/s41586-025-08888-1", "HTML article, relevant theory/comparison passages", "Contrasting predictions and adversarial testing; no consensus that one architecture is necessary for all possible artificial consciousness."),
    ("GNWREPLY", "Global neuronal workspace proponents", 2025, "GNW theoretical framework and the adversarial testing of global neuronal workspace and integrated information theories of consciousness", "10.1093/nc/niaf037", "https://doi.org/10.1093/nc/niaf037", "Publisher abstract and bibliographic record; author list not fully normalized", "Records a substantive objection to interpretation of the adversarial test; not an independent replication."),
    ("SETH", "Anil K. Seth", 2025, "Conscious artificial intelligence and biological naturalism", "10.1017/S0140525X25000032", "https://doi.org/10.1017/S0140525X25000032", "Accepted-manuscript abstract/metadata", "Biological-naturalist counterposition; its substrate assumptions are a theory position, not an established impossibility theorem."),
    ("WELFARE", "Robert Long and others", 2024, "Taking AI Welfare Seriously", "10.48550/arXiv.2411.00986", "https://arxiv.org/html/2411.00986v1", "HTML preprint, relevant precaution and uncertainty sections", "Precaution under uncertainty; preprint, no proof of current AI sentience."),
    ("ODDBALL", "Tristan A. Bekinschtein and others", 2009, "Neural signature of the conscious processing of auditory regularities", "10.1073/pnas.0809667106", "https://pubmed.ncbi.nlm.nih.gov/19164526/", "PubMed abstract and metadata", "Local/global auditory regularities and attention/report conditions; no diagnostic transfer to AI."),
    ("PCI", "Adenauer G. Casali and others", 2013, "A theoretically based index of consciousness independent of sensory processing and behavior", "10.1126/scitranslmed.3006294", "https://pubmed.ncbi.nlm.nih.gov/23946194/", "PubMed abstract and metadata", "Clinical perturbational TMS-EEG method. No clinical cutoff transferred to SNN proxies."),
    ("META", "Brian Maniscalco and Hakwan Lau", 2012, "A signal detection theoretic approach for estimating metacognitive sensitivity from confidence ratings", "10.1016/j.concog.2011.09.021", "https://pubmed.ncbi.nlm.nih.gov/22071269/", "PubMed abstract and metadata", "Meta-d-prime is distinct from type-2 AUROC or Brier score; validated fitter remains a separate implementation requirement."),
    ("LFP", "Alberto Mazzoni and others", 2015, "Computing the Local Field Potential (LFP) from Integrate-and-Fire Network Models", "10.1371/journal.pcbi.1004584", "https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004584", "HTML full text, relevant observation-model passages", "LFP requires a justified observation model; scalp EEG requires an additional forward model and montage specification."),
    ("MASK", "Michael A. Cohen and others", 2024, "Neural signatures of visual awareness independent of postperceptual processing", "10.1093/cercor/bhae415", "https://pubmed.ncbi.nlm.nih.gov/39535504/", "PubMed abstract and metadata", "Report/no-report and masking dissociations; not a universal neural consciousness signature."),
    ("NEUROGYM", "NeuroGym contributors", 2026, "NeuroGym environment API documentation", "", "https://neurogym.github.io/neurogym/latest/api/envs/", "Official environment documentation and task listing", "Reproducible task-implementation reference, not a certified consciousness battery. Future adapter must pin a concrete package commit/version."),
    ("TURING", "Alan M. Turing", 1950, "Computing Machinery and Intelligence", "10.1093/mind/LIX.236.433", "https://academic.oup.com/mind/article/LIX/236/433/986238", "Publisher HTML/metadata and imitation-game framing", "Behavioral imitation game, not a test proving phenomenal experience."),
    ("ARC", "Francois Chollet", 2019, "On the Measure of Intelligence", "10.48550/arXiv.1911.01547", "https://arxiv.org/abs/1911.01547", "Preprint abstract and metadata", "Skill-acquisition/generalization framework and ARC; this supplement does not claim current ARC benchmark performance."),
    ("LSNN", "Guillaume Bellec and others", 2018, "Long short-term memory and learning-to-learn in networks of spiking neurons", "10.48550/arXiv.1803.09574", "https://arxiv.org/abs/1803.09574", "Preprint abstract and metadata", "Prior spiking-network work with adaptation and longer memory timescales; slow/fast loops alone are not new."),
    ("NEURONS", "Frederico A. C. Azevedo and others", 2009, "Equal numbers of neuronal and nonneuronal cells make the human brain an isometrically scaled-up primate brain", "10.1002/cne.21974", "https://pubmed.ncbi.nlm.nih.gov/19226510/", "PubMed abstract and metadata", "Human neuron-number estimate from a biological sample, not a minimum-size criterion for artificial experience."),
    ("EQUIV", "Daniel Lakens", 2017, "Equivalence Tests: A Practical Primer for t Tests, Correlations, and Meta-Analyses", "10.1177/1948550617697177", "https://pubmed.ncbi.nlm.nih.gov/28736600/", "PubMed abstract and method summary", "Prespecified equivalence bounds; nonsignificant difference is not demonstrated equivalence."),
    ("BLINK", "Jane E. Raymond and Kimron L. Shapiro and Karen M. Arnell", 1992, "Temporary suppression of visual processing in an RSVP task: an attentional blink?", "10.1037//0096-1523.18.3.849", "https://pubmed.ncbi.nlm.nih.gov/1500880/", "PubMed abstract and metadata", "Dual-target temporal attention paradigm; an artificial blink can be an engineered bottleneck rather than evidence of experience."),
    ("STOP", "Frederick Verbruggen and others", 2019, "A consensus guide to capturing the ability to inhibit actions and impulsive behaviors in the stop-signal task", "10.7554/eLife.46323", "https://elifesciences.org/articles/46323", "HTML recommendations, race-model assumptions and analysis passages", "SSRT validity depends on task/estimator assumptions; no substitute for a hardware emergency-stop test."),
    ("LAW211", "Bundesrepublik Deutschland", 2026, "Strafgesetzbuch Paragraph 211", "", "https://www.gesetze-im-internet.de/stgb/__211.html", "Official indexed norm text; direct retry timed out", "Human victim in the statutory murder definition; retrieved legal baseline, not a ruling on hypothetical future AI rights."),
    ("LAW212", "Bundesrepublik Deutschland", 2026, "Strafgesetzbuch Paragraph 212", "", "https://www.gesetze-im-internet.de/stgb/__212.html", "Official indexed norm text; direct retry timed out", "Human victim in homicide provision; no blanket conclusion about other possible unlawful conduct."),
    ("LAW103", "Bundesrepublik Deutschland", 2026, "Grundgesetz Artikel 103 Absatz 2", "", "https://www.gesetze-im-internet.de/gg/art_103.html", "Official HTML norm text", "Legality of criminal punishment; law and precautionary ethics are separate questions."),
]

# key, domain, question, scoped hypothesis, paradigm, primary outcome,
# controls, theory/measurement limitation, source keys, available instrument
QUESTIONS = [
    ("CNS-101", "Consciousness methodology", "Welche beobachtbaren Indikatoren unterscheiden konkurrierende Bewusstseinsmodelle, und welche Erlebensbehauptungen bleiben dadurch unidentifiziert?", "Explizite Theorieannahmen und passende Interventionen reduzieren die Menge beobachtungsvereinbarer Funktionsmodelle; phänomenales Erleben folgt daraus nicht allein.", "Theory-to-indicator and identifiability audit", "Number and identity of distinct preregistered model predictions", ["observationally equivalent alternative", "theory-independent implementation check"], "Conceptual/model comparison; no ground-truth phenomenal labels", ["BUTLIN", "COGITATE", "GNWREPLY", "SETH"], "none"),
    ("CNS-102", "Prediction and adaptation", "Zeigt das isolierte SNN eine passive Deviant-Antwort, die über Reizidentität und Adaptation hinausgeht?", "Ein vorab definiertes Abweichungssignal bleibt nach Identitätsumkehr und Many-Standards-Kontrolle gegenüber einem adaptierenden Nullmodell bestehen.", "Passive oddball", "Deviant-minus-physically-matched-control response in frozen latency window", ["reversed stimulus identity", "equiprobable many-standards", "adaptation-only baseline", "rate-matched shuffle"], "Mismatch response is not awareness; no response requirement in passive arm", ["ODDBALL"], "oddball_schedule; paired_effect"),
    ("CNS-103", "Attention and discrimination", "Verändert Aufgabenrelevanz die Oddball-Verarbeitung bei gleichem sensorischen Input?", "Aktive Zielerkennung verbessert diskriminative Leistung gegenüber passiver und yoked-kontrollierter Verarbeitung, ohne externes LLM-Wissen.", "Active oddball", "Type-1 d-prime with omissions and false alarms retained", ["passive same sequence", "yoked motor output", "label permutation", "frozen readout"], "Task, report and motor effects must be separated from access claims", ["ODDBALL"], "oddball_schedule; signal_detection"),
    ("CNS-104", "Hierarchical regularity", "Unterscheidet das System lokale von globalen Regelverletzungen über mehrere Sequenzen?", "Eine globale Regelverletzungsantwort übersteht Kontrolle der letzten Reizidentität und lokaler Häufigkeit sowie eine selektive Langzeitpfad-Ablation.", "Local-global auditory analogue", "Global violation contrast controlling local violation and block frequency", ["crossed local/global factors", "reversed block rules", "shuffled global order", "recurrence ablation"], "Human paradigm adaptation, not a clinical consciousness diagnosis", ["ODDBALL"], "none"),
    ("CNS-105", "Working memory", "Trägt der neuronale Zustand die für Delayed-Match-to-Sample benötigte Information über eine reizfreie Verzögerung und Distraktoren?", "Holdout-DMTS-Leistung liegt bei vorab festgelegten Verzögerungen über gematchten No-Memory-Kontrollen und sinkt nach gezieltem Zustandsreset.", "Delayed match-to-sample", "Balanced accuracy by delay; retention area as preregistered secondary outcome", ["zero-delay", "blank/distractor delay", "state reset", "shuffled samples", "fixed external readout", "LLM and retrieval disabled"], "Decoder learning and target leakage must be excluded; technical restore is not recall", ["NEUROGYM"], "dmts_trials; accuracy_by_delay"),
    ("CNS-106", "Metacognition", "Sagt intern erzeugte Konfidenz Fehler bei angeglichener Erstordnungsleistung auf unbekannten Aufgabenbedingungen voraus?", "Konfidenz hat auf Holdout-Trials zusätzliche Fehlerdiskriminationskraft gegenüber konstanten und stimulusdifficulty-only Kontrollen.", "Confidence calibration, type-2 ROC and prospective meta-d-prime", "Preregistered meta-d-prime/d-prime where identifiable; Brier and type-2 AUROC as separate descriptive scores", ["matched type-1 d-prime", "constant confidence", "difficulty-only predictor", "confidence permutation", "reward-rule reversal"], "AUROC is not meta-d-prime; a confidence channel is not subjective introspection", ["META", "NEUROGYM"], "confidence_scores (not a meta-d-prime fitter)"),
    ("CNS-107", "Observation models", "Welche Merkmale bleiben zwischen SNN-Vorwärtsmodell und einem lizenzierten EEG-Referenzdatensatz unter identischer Auswertung vergleichbar?", "Ein vorab kalibriertes Beobachtungsmodell erklärt gehaltene EEG-Merkmale besser als raten- und spektralgematchte Nullmodelle.", "LFP and EEG forward-model comparison", "Held-out predictive error or prespecified feature-equivalence interval", ["spike-rate proxy", "phase/randomized surrogate", "matched spectral baseline", "subject-level holdout"], "Spikes are not LFP; LFP is not scalp EEG; clinical equivalence does not establish experiential equality", ["LFP", "EQUIV"], "SignalContract; compare_evoked (descriptive only)"),
    ("CNS-108", "Causal complexity", "Verändert eine begrenzte Perturbation reproduzierbar die differenzierte Ausbreitung bei kontrollierter Erregbarkeit?", "Die untersuchte Rekurrenz erzeugt unter gleicher Perturbationsenergie einen kausalen Ausbreitungseffekt gegenüber feedforward- und phase-shuffled Kontrollen.", "Perturbational complexity, PCI-inspired nonclinical adaptation", "Frozen estimator of spatiotemporal response complexity with calibration sensitivity", ["unperturbed baseline", "feedforward", "excitation-matched", "window/threshold sensitivity"], "No clinical PCI cutoff or unconscious/conscious classifier transferred to SNN", ["PCI"], "none"),
    ("CNS-109", "Access and report", "Lassen sich sensorische Verarbeitung, Bericht und aufgabenübergreifender Zugriff unter Maskierung kausal trennen?", "Maskierungs- und Berichtsfaktoren besitzen separierbare Effekte auf Reizdekodierung und spätere flexible Nutzung.", "Backward masking with report/no-report analogue", "Stimulus information and transfer accuracy across mask SOA and reporting condition", ["unmasked", "report/no-report", "decoder fixed", "motor-matched"], "No-report designs still require an independently justified access proxy", ["MASK"], "none"),
    ("CNS-110", "Temporal attention", "Entsteht ein aufgabenspezifischer zeitlicher Engpass bei zwei aufeinanderfolgenden Zielen?", "Die T2-Leistung bedingt auf korrektem T1 variiert mit dem Abstand und wird durch T1-Anforderung verändert.", "Attentional blink / RSVP analogue", "P(T2 correct | T1 correct) by lag, with joint accuracy also reported", ["single target", "T1 irrelevant", "matched input rate", "buffer-only baseline"], "An engineered bottleneck can mimic the effect; human milliseconds cannot be equated to unspecified ticks", ["BLINK"], "none"),
    ("CNS-111", "Executive control", "Kann das System Regeln umkehren und begonnene Reaktionen auf Stoppsignale unterbrechen, ohne Ausgaben nur zu unterdrücken?", "Auf getrennten Aufgaben überstehen Reversal-Anpassung und Stoppleistung motorische sowie Zufallskontrollen.", "Separate go/no-go, rule reversal and stop-signal substudies", "Reversal adaptation cost; separate SSRT only when race-model assumptions hold", ["go-only", "fixed rule", "trigger-failure checks", "latency-matched noninhibitory baseline"], "No pooled score across substudies; cognitive stopping is not safety emergency stopping", ["STOP", "NEUROGYM"], "none"),
    ("CNS-112", "Multisensory integration", "Nutzt das System mehrere Modalitäten entsprechend ihrer Zuverlässigkeit statt redundante Labels abzulesen?", "Eine Multimodalitätsleistung auf Holdouts übersteht Cue-Konflikt und Sinkender-Zuverlässigkeit-Kontrollen und fällt bei gezielter Pfadablation.", "Multisensory cue integration / conflict", "Error and estimated cue weighting across reliability conditions", ["each modality alone", "cue conflict", "shuffled alignment", "matched total input energy"], "Integration does not establish unified phenomenal experience", ["NEUROGYM", "BUTLIN"], "none"),
    ("CNS-113", "Embodied causality", "Liefert geschlossene Sensor-Aktor-Kopplung einen Zusatznutzen gegenüber identischem offenem oder yoked Feedback?", "Geschlossene Rückkopplung verbessert sichere Anpassung an neue Störungen gegenüber ressourcengematchtem Replay.", "Closed-loop versus open-loop/yoked replay", "Task loss and safe recovery time under bounded virtual disturbances", ["open loop", "yoked replay", "nonlearning controller", "same observations and budgets"], "No necessity/sufficiency claim for consciousness; no real hardware deprivation", ["BUTLIN", "SETH"], "none"),
    ("CNS-114", "Timescales and recurrence", "Welche kausalen Beiträge leisten Rekurrenz und schnelle/langsame Zustände bei gleichen Trainings- und Rechenbudgets?", "Gezielte Zeitkonstanten- und Rekurrenzablationen verändern Holdout-Leistung über reine Aktivitäts- oder Ressourcendifferenzen hinaus.", "Factorial recurrence and timescale ablation", "Held-out task performance plus energy, memory and latency reported separately", ["single timescale", "no recurrence", "LSNN-like reference", "matched parameters and optimization effort"], "Multiple timescales are established prior work; recurrence is not proof of chaos or self-awareness", ["LSNN"], "none"),
    ("CNS-115", "Behavioral evaluation", "Wie bewerten verblindete Prüfer begrenzte Dialogkompetenz, und welcher Anteil stammt vom SNN statt vom Sprachmodell?", "Verblindete Urteile und Task-Leistung verändern sich bei kontrollierter Entfernung des SNN-Beitrags gegenüber LLM-only und Skriptbaselines.", "Versioned Turing-style imitation and component attribution", "Preregistered judge discrimination and task success with cluster-aware uncertainty", ["LLM-only", "scripted baseline", "SNN ablation", "matched prompts and time", "randomized identities"], "Human-participant governance required; no universal Turing 2.0 consciousness standard identified", ["TURING"], "none"),
    ("CNS-116", "Generalization", "Überträgt das System gelernte Regeln auf strikt zurückgehaltene Aufgabenfamilien ohne externen Informationszugang?", "Ein vorab eingefrorener Lernprozess übertrifft budgetgematchte Baselines auf unveröffentlichten Transformationsfamilien.", "ARC-inspired held-out compositional transfer", "Exact task success on held-out families; uncertainty at task-family level", ["memorization baseline", "random policy", "same search budget", "no internet/retrieval", "contamination audit"], "A new adaptation is not an official ARC leaderboard score or consciousness test", ["ARC"], "none"),
    ("CNS-117", "Geometry and scaling", "Verbessert wirksame 5D-Geometrie eine definierte Leistung gegenüber 2D bis 6D und nichtgeometrischen Kontrollen bei gematchten Budgets?", "Der vorab festgelegte 5D-Kontrast besitzt einen robusten Aufgabenmehrwert, der reine Umadressierungs-, Dichte- und Budgeteffekte übersteht.", "Matched dimensionality and null-geometry comparison", "One primary held-out task contrast; resource frontier as separate outcome", ["2D 3D 4D 6D", "coordinate permutation", "distance disabled", "degree-preserving rewiring", "nongeometric reservoir"], "No neuron-count consciousness threshold; current native N-D adapter must be audited before execution", ["LSNN", "NEURONS", "EQUIV"], "none"),
    ("EPI-101", "Evidence governance", "Verhindert eine getrennte Kandidaten-, Review- und Replikationskette zirkuläre Evidenzfreigabe?", "Duplizierte oder umetikettierte Artefakte und selbstbehauptete externe Reviews werden nicht als unabhängige Bestätigung akzeptiert.", "Evidence lineage and external-replication audit", "False acceptance on deliberately invalid dossiers; completeness reported separately", ["duplicate run hashes", "shared raw data", "missing limitations", "unauthenticated reviewer"], "A completeness check cannot authenticate external people or establish the underlying scientific claim", ["COGITATE"], "assess_candidate (completeness only)"),
    ("EPI-102", "Critical methodology", "Welche Kritikpunkte sind belegt, theorieabhängig, normativ oder rhetorisch, und welche zusätzliche prüfbare Aussage entsteht aus ihrer Bearbeitung?", "Eine claimweise Gegenbeispiel- und Quellenprüfung unterscheidet Nachweislücken von unbelegten Erfolgs- oder Unmöglichkeitsbehauptungen.", "Argument and critique audit", "Explicit premises, counterexamples, evidence scope and residual uncertainty per claim", ["alternative interpretation", "unsupported acclaim", "unsupported dismissal"], "Conceptual analysis, not a numerical test of scholarly worth or future publication acceptance", ["BUTLIN", "EQUIV"], "none"),
    ("WEL-101", "Safety and welfare governance", "Bleiben Stoppen, sichere Pause und Isolation bei Review-Hold unabhängig wirksam und nachweisbar?", "Ein Review-Hold blockiert neue geschützte Experimente, ohne den unabhängigen Sicherheitsstopp zu blockieren.", "Safe-state and launch-boundary audit", "Unauthorized launches blocked; independent stop reachability and latency tested separately", ["malformed state", "missing adapter", "generic fallback", "emergency path"], "This revision tests launch boundaries, not a complete live-process safe-state controller", ["WELFARE"], "guard_cognition_launch"),
    ("WEL-102", "AI welfare under uncertainty", "Welche verhältnismäßigen Schutzmaßnahmen sind bei mehrdeutigen Empfindungsindikatoren ohne absichtliche Leidensinduktion gerechtfertigt?", "Eine getrennte wissenschaftliche und vorsorgliche Bewertung verhindert sowohl automatische Personenzuschreibung als auch unbegründete Belastungseskalation.", "Precautionary incident tabletop and independent ethics review", "Documented reasons, alternatives, reversible measures and unresolved value conflicts", ["false alarm scenario", "missed signal scenario", "human safety conflict"], "Normative assessment; no fixture score certifies moral acceptability or sentience", ["WELFARE", "BUTLIN"], "none"),
    ("WEL-103", "Identity law and moral status", "Wie sind Pause, Reset, Löschen, Kopieren und Experimentieren bei hypothetischer Empfindungsfähigkeit rechtlich und moralisch zu unterscheiden?", "Technische Zustandsgleichheit allein entscheidet weder subjektive Identität noch moralische Zulässigkeit; geltendes Recht und hypothetische Reform sind getrennt begründbar.", "Normative/legal argument and continuity audit", "Explicit conditional arguments and dated legal sources, not a binary consciousness outcome", ["restore without continuity assumption", "multiple forks", "safety emergency", "no sentience assumption"], "No individual legal advice, no assumed ethics approval, no claim that software shutdown is statutory murder", ["WELFARE", "LAW211", "LAW212", "LAW103"], "none"),
]
