import sys
sys.path.insert(0, ".")
import hashlib

lines = []
def L(s=""):
    lines.append(s)

# Docstring
L('"""Restore Determinism A/B/C — Alpha.5 Restore-and-Continue proof.')
L('')
L('This test implements the canonical A/B/C protocol with a tick-absolute')
L('stimulus schedule and real subprocess-based fresh-process restore.')
L('')
L('K = 500')
L('N = 1000')
L('')
L('A (reference):')
L('    fresh process -> 0 -> N uninterrupted')
L('')
L('B (in-process restore via restore_full):')
L('    fresh process -> 0 -> K')
L('    write production snapshot + checkpoint')
L('    call production restore_full() -> new RestoredNeuralNetwork')
L('    continue K -> N')
L('')
L('C (fresh-process restore):')
L('    process 1: 0 -> K -> write snapshot/checkpoint -> exit')
L('    process 2: load from filesystem only -> restore_full() -> continue K -> N')
L('')
L('Required result:')
L('    digest_A(N) == digest_B(N) == digest_C(N)')
L('    AND pid_C1 != pid_C2')
L('"""')
L('')
L('from __future__ import annotations')
L('')
L('import hashlib')
L('import json')
L('import os')
L('import subprocess')
L('import sys')
L('import time')
L('from pathlib import Path')
L('from typing import Any')
L('')
L('import pytest')
L('')
L('from src.core.network import Brain5DConfig, NeuralNetwork')
L('from src.core.spatial_index import linear_to_5d')
L('from src.homeostasis.engine import HomeostasisEngine')
L('from src.learning.learning_engine import LearningEngine')
L('from src.storage.checkpoint import capture_runtime_checkpoint, write_runtime_checkpoint')
L('from src.storage.core_restore import restore_full')
L('from src.storage.runtime import StorageRuntimeConfig, StorageSession')
L('')
L('K: int = 500')
L('N: int = 1000')
L('SEED: int = 42')
L('')
L('ARTIFACT_DIR = Path(__file__).resolve().parent.parent / "research" / "generated" / "verification"')
L('ARTIFACT_PATH = ARTIFACT_DIR / "restore_determinism.json"')
L('SUBPROCESS_WORKER = Path(__file__).resolve().parent / "_restore_worker.py"')
L('')
L('STIMULUS_INTERVAL: int = 50')
L('STIMULUS_AMPLITUDE: float = 30.0')
L('NUM_STIMULATED_NEURONS: int = 3')
L('')
L('')
L('def _config() -> dict[str, Any]:')
L('    return {')
L('        "seed": SEED,')
L('        "dimensions": [5, 5, 1, 1, 1],')
L('        "initial_neurons": 25,')
L('        "simulation": {"dt_ms": 1.0, "max_delay": 5, "debug_invariants": True},')
L('        "network": {"initial_connections_per_neuron": 3, "neighbour_radius": 2.0, "weight_min": 0.0, "weight_max": 0.5},')
L('        "neuron": {"a": 0.02, "b": 0.2, "c": -65.0, "d": 8.0},')
L('        "energy": {"initial": 1.0, "spike_cost": 0.001},')
L('        "topology": {"input": {"dimension": "x", "coordinate": 0}, "output": {"dimension": "x", "coordinate": 4}},')
L('        "homeostasis": {"enabled": True, "target_rate_hz": 5.0, "rate_tau_ticks": 200.0},')
L('        "stdp": {"enabled": True, "a_plus": 0.1, "a_minus": 0.12, "tau_plus": 20.0, "tau_minus": 20.0},')
L('        "eligibility": {"enabled": True, "tau_ticks": 200.0},')
L('        "reward": {"enabled": True, "learning_rate": 0.01, "delay_ticks": 5},')
L('    }')
L('')
L('')
L('def _create_network(config: dict[str, Any]) -> NeuralNetwork:')
L('    import random')
L('    rng = random.Random(config["seed"])')
L('    b5d_config = Brain5DConfig.from_dict(config)')
L('    net = NeuralNetwork(b5d_config, rng)')
L('    dims = config["dimensions"]')
L('    for i in range(config.get("initial_neurons", 25)):')
L('        net.add_neuron(linear_to_5d(i, tuple(dims)))')
L('    net.set_input_output_cells("x", 0, "x", dims[0] - 1)')
L('    net.initialize_random_connections(3, 2.0)')
L('    return net')
L('')
L('')
print("Part 1 generated,", len(lines), "lines")
with open("tests/test_restore_determinism_abc.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("Written")
